spring:
  datasource:
    url: jdbc:mysql://prod-db.example.com:3306/mydb_prod
    username: prod_user
    password: prod_password
    
spring:
  datasource:
    url: jdbc:mysql://prod-db.example.com:3306/mydb_prod
    username: prod_user
    password: prod_password
