spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abisekraj94/config-repo
          # Or you can use a local folder:
          # uri: file:///path/to/local/repo
          searchPaths:
            - config
          cloneOnStart: true

spring:
  cloud:
    config:
      uri: http://localhost:8888  # URL of your Config Server
      name: application  # Application name, matching the name in the repo
      profile: local  # Active profile, could be local, test, prod, etc.
      label: master  # The label (git branch or label, for example)
